# Generated by Django 4.1.1 on 2022-09-27 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 17, 0, 27, 226235, tzinfo=datetime.timezone.utc)),
        ),
    ]
